//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurante
    {
        public int IdRestaurante { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public string Dirección { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<int> IdReceta { get; set; }
    
        public virtual Pai Pai { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
